generate_content:
  name: Generate content
  description: "Generate a response from the Groq API."
  fields:
    config_entry:
      name: Config entry
      description: "The config entry to use for this service."
      required: true
      selector:
        config_entry:
          integration: groq_cloud_api
    prompt:
      name: Prompt
      description: "The prompt to send to the Groq API."
      required: true
      selector:
        text:
          multiline: true
